import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NightsStayIcon from "@mui/icons-material/NightsStay";
import { useEffect } from "react";
import Weather from "../api/Weather";
import { useState } from "react";

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [location, setLocation] = useState({ lat: 0, lon: 0 });
  const [data, setData] = useState(null);

  useEffect(() => {
    window.navigator.geolocation.getCurrentPosition((position) => {
      setLocation({
        lat: position.coords.latitude,
        lon: position.coords.longitude,
      });
    });
    setLoading(false);
  }, []);

  useEffect(() => {
    Weather.get(`/current?lon=${location.lon}&lat=${location.lat}`).then(
      (res) => {
        setData(res.data);
      }
    );
  }, [loading, location]);

  return (
    // <div className="max-w-md sm:max-w-xl md:max-w-2xl lg:max-w-4xl xl:max-w-6xl min-h-screen mx-auto">
    <div>
      <Head>
        <title>Weather Quo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex flex-col text-white py-8 px-4">
        <h1 className="font-light text-3xl h-16 bg-black">
          {data ? data.name : "Las Vegas"}
        </h1>
        <p className="text-7xl">
          {data ? data.main.temp : ""}
          <sup>°C</sup>
        </p>
        <p>{`${location.lat}${location.lon}`}</p>
        <p className="">{data ? data.weather[0].main : ""}</p>
      </main>
    </div>
  );
}
