import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NightsStayIcon from "@mui/icons-material/NightsStay";

export default function Home() {
  return (
    <div className="max-w-md sm:max-w-xl md:max-w-2xl lg:max-w-4xl xl:max-w-6xl min-h-screen mx-auto border">
      <Head>
        <title>Weather Quo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-gradient-to-t from-indigo-400 to-sky-400 flex items-center justify-center flex-col text-white">
        <h1 className="font-bold text-3xl">Las Vegas</h1>
        <NightsStayIcon fontSize="large" className="animate-bounce my-2" />
        <p className="">Cloudy</p>
        <p className="">72°</p>
      </main>
    </div>
  );
}
